[package]
name = "barista_alignment"
version = "0.0.0"
edition = "2021"

[dependencies]
rosidl_runtime_rs = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }
unique_identifier_msgs = "*"
action_msgs = "*"
builtin_interfaces = "*"
std_msgs = "*"

[features]
serde = ['dep:serde', 'rosidl_runtime_rs/serde', 'unique_identifier_msgs/serde', 'action_msgs/serde', 'builtin_interfaces/serde', 'std_msgs/serde']
